apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-home-pvc
  namespace: confluence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-postgres-pvc
  namespace: confluence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi