apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30040
    - name: agent
      port: 50000
      targetPort: 50000
      nodePort: 30041
  selector:
    app: jenkins