apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-postgres
  namespace: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira-postgres
  template:
    metadata:
      labels:
        app: jira-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: jiradb
            - name: POSTGRES_USER
              value: jirauser
            - name: POSTGRES_PASSWORD
              value: jirapassword
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jira-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jira-postgres
  namespace: jira
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: jira-postgres