apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-home-pvc
  namespace: jira
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-postgres-pvc
  namespace: jira
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi