apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-data-pvc
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-postgres-pvc
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi