apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: artifactory
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30881
  selector:
    app: artifactory